### PR TITLE
Nextjs-Rewrite II

### PR DESCRIPTION
**Pull request by bbayazit16**
This pull request completes the second half of nextjs-rewrites.

### CODE REVIEW

**Review by hydrabeer — APPROVED** [review]
LGTM

**Review by JasonBarahan — COMMENTED** [review]
Changes look good. Just need to figure out why the build fails (the deploy logs take ages to load for me).

**Comment by JasonBarahan** [comment]
Actually, I have a feeling the build's failing due to an outage. Give it until tomorrow morning and I'll request the tests be rerun. It should work.

**Comment by JasonBarahan** [comment]
Update: not an outage

**Comment by JasonBarahan** [comment]
For some odd reason Netlify's build statuses were not being reflected here. 
(I checked the webhooks, they were OK)

**Pull request merged**
